# Site settings
title: SP 1500-100 CDF for Election Results Reporting
description: "Initial MarkDown version of NIST Special Publication: SP 1500-100"
baseurl: "/ElectionResultsReporting" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: ElectionResultsReporting

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /ElectionResultsReporting/

host: 0.0.0.0
